### PR TITLE
[#523] Added help_text in Change Permission View

### LINKED ISSUE #523: The state of selected fields is not tracked in Change Permission View
### Product versie / Product version

3.0.0

### Omschrijf het probleem / Describe the bug

Problem found in PR: https://github.com/maykinmedia/objects-api/pull/508

If you change the `objecttype` in the dropdown and then change it back, the previously selected fields won't be reselected, even if they're saved in the database.

`admin/token/permission/<objecttype_id>/change/`

Example: https://github.com/maykinmedia/objects-api/pull/508#pullrequestreview-2578556174

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by danielmursa-dev**
Fixes #523

### CODE REVIEW

**Review by Floris272 — APPROVED** [review]
One minor thing: Within the codebase `authorization` spelled with `z` everywhere else.

File: src/objects/js/components/admin/permissions/permission-form.js [hunk 1]
```diff
@@ -65,6 +65,7 @@ const PermissionForm = ({objectFields, tokenChoices, objecttypeChoices, modeChoi
                 id="id_object_type"
                 label="Object type:"
                 choices={objecttypeChoices}
+                helpText="Changing the object_type will not maintain the previously selected authorization fields."
```
Comment (stevenbal) [inline src/objects/js/components/admin/permissions/permission-form.js:68]: Let's use the name as it is displayed in the admin
```suggestion
                helpText="Changing the Object type will not maintain the previously selected authorization fields."
```

**Review by stevenbal — CHANGES_REQUESTED** [review]

**Review by stevenbal — APPROVED** [review]
